// Traduce los `codigoError` del backend (catálogo estable `session/comandos/codigosDeError.ts`) a un mensaje que entienda el jugador.
// Si el backend da el motivo concreto (`detalleError`, 2026-10-07) se enseña ese (`errorDeRechazo` en `main.ts`); esto es para los rechazos que solo
// traen el código. Lo que no esté aquí sale tal cual.
const MENSAJES: Record<string, string> = {
  // Facción y membresía
  'faccion.nombre_vacio': 'La Facción necesita un nombre.',
  'faccion.nombre_duplicado': 'Ya existe una Facción con ese nombre: elige otro.',
  'faccion.sigilo_invalido': 'El sigilo no es válido: alguna pieza no es del catálogo, o el color principal y el secundario del fondo son el mismo.',
  'faccion.sigilo_duplicado': 'Otra Facción ya lleva exactamente ese sigilo: cambia alguna pieza o color.',
  'faccion.ya_pertenece': 'Ya perteneces a una Facción: tienes que dejarla antes.',
  'faccion.cooldown_creacion': 'Creaste o dejaste una Facción hace poco: tienes que esperar a que acabe el enfriamiento de creación.',
  'faccion.no_pertenece': 'No perteneces a ninguna Facción.',
  'faccion.no_existe': 'Esa Facción no existe.',
  'faccion.invalida': 'La Facción no admite esa acción ahora (comprueba si eres su Rey o su Embajador).',
  'faccion.capital_invalida': 'Esa plaza no puede ser la capital.',
  'cargo.invalido': 'No puedes asignar ese cargo: comprueba que seas Rey o Gobernador y que la persona sea ciudadana.',
  'anexion.invalida': 'La anexión no es posible ahora.',
  'anexion.no_existe': 'Esa propuesta de anexión ya no existe.',
  'anexion.caducada': 'La propuesta de anexión caducó.',
  'fusion.invalida': 'La fusión no es posible ahora.',
  'fusion.no_existe': 'Esa propuesta de fusión ya no existe.',
  'fusion.caducada': 'La propuesta de fusión caducó.',
  'diplomacia.invalida': 'La diplomacia no admite esa acción ahora.',
  'diplomacia.relacion_no_indicada': 'Falta indicar la relación.',
  'politica.invalida': 'Esa política no se puede adoptar ahora.',
  // Héroe y campamento
  'heroe.invalido': 'El héroe no puede hacer eso (no cabe en el Liderazgo o el cupo, falta algo, o el nombre está vacío).',
  'heroe.ya_existe': 'Ya tienes un héroe en esta partida.',
  'heroe.nombre_vacio': 'Tu héroe necesita un nombre.',
  'heroe.campamento_desconocido': 'Ese campamento de mercenarios no existe.',
  'campamento.desconocido': 'Ese campamento de mercenarios no existe.',
  'campamento.no_existe': 'Ese campamento no existe.',
  'campamento.lejos': 'Estás demasiado lejos: hay que estar dentro o con la columna a la puerta.',
  'campamento.proteccion': 'Junto a un campamento de mercenarios nadie inicia un combate.',
  'mercenarios.invalido': 'El campamento no admite esa acción: comprueba que residas en él, que haya existencias y que tengas con qué pagar.',
  'alijo.desconocido': 'Ese alijo no existe.',
  'alijo.invalido': 'No puedes abrir ese alijo ahora: hay que estar en el sitio.',
  // Movimiento y combate
  'jugador.sin_columna': 'No tienes columna en el mapa: sal al mundo primero.',
  'jugador.no_existe': 'Ese jugador no existe.',
  'movilizacion.invalida': 'La columna no puede hacer eso ahora (distancia, estado o composición).',
  'combate.invalido': 'Ese combate no es posible ahora.',
  'ejercito.no_existe': 'Esa columna ya no existe.',
  'puerta.invalida': 'No estás a la puerta.',
  'batalla.no_existe': 'Esa batalla ya no existe.',
  'batalla.bloqueado': 'Eso está en una batalla activa y no se toca.',
  'batalla.invalida': 'No puedes unirte o actuar en esa batalla.',
  'batalla.ya_asignada': 'Esa batalla ya tiene instancia asignada.',
  // Plazas, economía y resto
  'asentamiento.no_existe': 'Esa plaza no existe.',
  'caravana.no_existe': 'Esa caravana no existe.',
  'caravana.no_aparcada_aqui': 'Esa caravana no está aparcada aquí.',
  'acuerdo.no_existe': 'Ese acuerdo no existe.',
  'orden.no_existe': 'Esa oferta ya no existe.',
  'construccion.invalida': 'No se puede construir eso ahora (nivel, cupo, recursos o cargo).',
  'expansion.invalida': 'No se puede expandir así.',
  'fundacion.invalida': 'No se puede fundar aquí (agua, otra plaza o campamento demasiado cerca).',
  'fundacion.sin_caravana': 'Para fundar necesitas llevar enganchada, como titular, una Caravana de Fundación.',
  'mercado.orden_invalida': 'La oferta no es válida.',
  'tropas.reclutamiento_invalido': 'No se puede reclutar eso ahora (cupo, recursos o edificio).',
  'comercio.caravana_invalida': 'La caravana no admite esa orden.',
  'comercio.trueque_invalido': 'El trueque no es válido.',
  'recinto.invalido': 'La muralla no admite esa acción.',
  'ascenso.invalido': 'La plaza aún no puede subir de nivel.',
  'tecnologia.adopcion_invalida': 'No se puede adoptar esa tecnología ahora.',
  'aedas.venta_invalida': 'No se puede vender eso al aeda.',
  'aedas.epica_invalida': 'La épica no es válida.',
  'intel.invalida': 'La compra de intel no es posible: comprueba la taberna, el oro, el cupo de Miradas y el enfriamiento.',
  'reserva.sin_tesorero': 'La plaza no tiene Tesorero.',
};

/** El mensaje del jugador para un código del backend; si no se conoce, el propio texto. */
export function explicarError(codigoOTexto: string): string {
  return MENSAJES[codigoOTexto] ?? codigoOTexto;
}
